export const LOADING_USER = 'LOADING_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';

export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const LOADING_DATA = 'LOADING_DATA';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_QUESTION = 'SET_QUESTION';
export const SAVE_QUESTION = 'SAVE_QUESTION';
export const UNSAVE_QUESTION = 'UNSAVE_QUESTION';
export const POST_QUESTION = 'POST_QUESTION';
export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
